### PR TITLE
fix: focus on get-one-here button in bc-start

### LINKED ISSUE #182: Improve accessibility
Tabbing / Keyboard access should work in all places. Some elements (like the button below) should be focused by default.

image

### PR DESCRIPTION
**Pull request by krrish-sehgal**
fixes #182 

https://github.com/user-attachments/assets/46e0a6d4-b4a6-45b3-882d-a1bd365079c7

### CODE REVIEW

File: src/components/bc-start.ts [hunk 1]
```diff
@@ -71,16 +73,18 @@ export class Start extends withTwind()(BitcoinConnectElement) {
...
-              <h1 class="mt-8 ${classes['text-neutral-primary']} text-center">
+              <p class="mt-8 ${classes['text-neutral-primary']} text-center">
                 Don't have a bitcoin lightning wallet?
-                <a
-                  class="no-underline font-bold ${classes.interactive} ${classes[
+                <button
+                  class="font-bold ${classes.interactive} ${classes[
                     'text-brand-mixed'
-                  ]} "
+                  ]} bg-transparent border-none p-0 underline text-sm"
```
Comment (rolznz) [inline src/components/bc-start.ts:81]: did you intend to add these excess classes again? I think they can be removed

**Review by rolznz — APPROVED** [review]
tACK

File: src/components/bc-start.ts (hunk 1 above)
Comment (krrish-sehgal) [reply src/components/bc-start.ts]: something I picked up while writing tailiwind, reverted!
